# -*- coding: utf-8 -*-
"""VIGNERE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hcr0Sy2F7ktMcGJJr7StNJfrz8SBSIC0

## **ADDITIONAL - VIGENERE CIPHER**
"""

num = '0123456789'
lower = 'abcdefghijklmnopqrstuvwxyz'
upper = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

def encryption(pt, key):
    ct = ''
    for char in pt:
        if char in lower:
            inx = lower.index(char)
            ct += lower[(inx+key)%26]
        
        elif char in upper:
            inx = upper.index(char)
            ct += upper[(inx+key)%26]

        elif char == ' ':
            ct += ' '
            
        elif char in num:
            inx = num.index(char)
            ct += num[(inx+key)%10]
        
        else:
            ct += char

    return ct

alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

alpha = {}
for i, char in enumerate(alphabets):
    alpha[char] = i

key_list = list(alpha.keys())
val_list = list(alpha.values())

print(alpha)

cipher = {
    'A':'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
}

for key in range(1,26):
    ct = encryption(cipher['A'], key)
    cipher[ct[0]] = ct

print(cipher)

def vigenere_encryption(pt, key):
    ct = ''
    n = len(pt)
    for row, col in zip(pt,key):
        if row == ' ':
            ct += ' '
        else:
            inx = alpha[col]
            ct += cipher[row][inx]

    return ct

def vigenere_decryption(ct, key):
    pt = ''
    n = len(ct)
    for col, row in zip(ct,key):
        if (col == ' '):
            pt += ' '
        else:
            inx = cipher[row].index(col)
            pt += key_list[val_list.index(inx)]

    return pt

pt = input('ENTER INPUT STRING: ')
key = input('ENTER ENCRYPTION KEY: ')
#pt = 'JIZGIELULTAAVEWGFNMYUGUEHAWHBCKGOGRTDCNHBVHN'
#key = 'CONGRATULATIONS'
#key = 'BNMFQZSTKZSHNMR'
# CT = CPPJ
while ( len(key) < len(pt) ):
    key += key

key = key[:len(pt)]

print('PLAIN TEXT:',pt)
print('KEY:', key)

ct = vigenere_encryption(pt, key)
print('CIPHERED TEXT:', ct)

new_pt = vigenere_decryption(ct, key)
print('DECIPHERED TEXT:', new_pt)

